apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: laravel-cicleci-example
  name: laravel-cicleci-example
  namespace: default
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: laravel-cicleci-example
      name: laravel-cicleci-example
    spec:
      containers:
      - image: docker-image-laravel-circleci-example
        imagePullPolicy: IfNotPresent
        name: laravel-circleci-example  
      dnsPolicy: ClusterFirst
      restartPolicy: Always