version: 2

jobs: 
  build: 
    docker:  
      - image: ambientum/php:7.3
    steps:
      - checkout
      - restore_cache:
            keys:
              - composer-v1-{{ checksum "composer.lock" }}
              - composer-v1-
      - run: 
          name: Install dependencies (Composer)
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Run PHPCS PSR2
          command: vendor/bin/phpcs --standard=psr2 app